### ISSUE TITLE
browser extension for dealing with github issues

### ISSUE THREAD

**Issue by retlehs** [roots/guidelines#1]
see https://github.com/nashby/jose-vs-oss

**Comment by austinpray** [comment]
😎😎😎😎

**Comment by QWp6t** [comment]
:heart: :green_heart: :blue_heart: :yellow_heart: :purple_heart:

**Comment by retlehs** [comment]
https://chrome.google.com/webstore/detail/github-canned-responses/lhehmppafakahahobaibfcomknkhoina
